### ISSUE TITLE
Pre-filtering?

### ISSUE THREAD

**Issue by dkoslicki** [smangul1/MiCoP#1]
Did you want to implement the [CMash](https://github.com/dkoslicki/CMash) pre-filtering to enable profiling of bacteria as well?

**Comment by nlapier2** [comment]
I am interested in including CMash, but we'd have to figure out some clever way of avoiding the re-indexing of the reduced databases after applying CMash. Normally indexing a database with something like BWA would only have to be done once, but every time we reduce the database based on some reads using CMash, we'd have to re-index it before performing alignment.
