### ISSUE TITLE
Indices.zip impossible to download during setup

### ISSUE THREAD

**Issue by Leob44** [smangul1/MiCoP#10]
Hello, 

The tools appears to be outdated. I get this weird error when executing setup.sh: 

`Archive:  indices.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of indices.zip or
        indices.zip.zip, and cannot find indices.zip.ZIP, period.
`

I tried downloading it manually but it seems it is not on google drive anymore (too heavy ? )

**Comment by almicach** [comment]
Hi, I have the same problem. Did you figure out how to solve it?

**Comment by nlapier2** [comment]
Sorry about that -- looks like the workaround enabling wget from google drive is no longer working. I'll work on getting the file up on zenodo and update the link. In the meantime, if you are ok with downloading from the browser, you can use this link: https://drive.google.com/u/1/uc?id=1iYEC9xwXReCoxeXOFLwoW82tmbCt9QR7&export=download

**Comment by nlapier2** [comment]
Update: the data is up on zenodo now. Please try the new setup.sh script.

**Comment by Angel-Popa** [comment]
Hi Nathan, 

Thank you for the tool.

I kept having an error with the setup.py script. After reviewing the code and reading issue [1629 ](https://github.com/zenodo/zenodo/issues/1629) on the Zenodo GitHub page, I modified the script to include the Zenodo REST API, which avoids problems with wget, like:

```
#!/bin/bash
curl https://zenodo.org/record/6399965/files/indices.zip?download=1 --output indices.zip
mv indices.zip data/indices.zip
cd data
unzip indices.zip
rm indices.zip
cd ..
```
