### ISSUE TITLE
Fungal / viral database

### ISSUE THREAD

**Issue by theo-allnutt-bioinformatics** [smangul1/MiCoP#2]
Hi,

can you please provide the Entrez terms used to download your databases, or provide the raw fasta files?

Thanks,

T

**Comment by nlapier2** [comment]
Hi,

Thanks for bringing this up. I've added download links for the raw FASTA database files to the README. For convenience I'll also include them here.

Viruses: https://drive.google.com/file/d/1qQGddyD4Zkj-LaT6vLe9kP4uDCBJHH85/view?usp=sharing

Fungi: https://drive.google.com/file/d/14E0G0w_gUJizYsjyLUNzd7J7frrMaeMJ/view?usp=sharing

Best,
Nathan
