### ISSUE TITLE
compute-abundances error

### ISSUE THREAD

**Issue by bouquetj** [smangul1/MiCoP#4]
I'm getting the following error. How can I fix it? Thanks!

python compute-abundances.py -h
  File "compute-abundances.py", line 282
    lev_res = {i:[] for i in range(len(RANKS))}
                      ^
SyntaxError: invalid syntax

**Comment by nlapier2** [comment]
Thanks for the feedback. What is your python version? (Check with "python --version".) It may be that this syntax is only available in certain versions of python.

**Comment by bouquetj** [comment]
Got it! Tried with 3 different versions (2.66, 2.7.14 and 3.6.7)
It worked with python 2.7.14. 
FYI with python 3.6.7 was getting an error line 119 instead of line 282
Thanks!

**Comment by nlapier2** [comment]
Thanks, this helps a lot. I will look into making this work for different versions of python.

**Comment by nlapier2** [comment]
It should be compatible with both python 2 and python 3 now.
