### ISSUE TITLE
Failing to open file when using --paired

### ISSUE THREAD

**Issue by SimenHyllHansen** [smangul1/MiCoP#5]
Hi! I have paired-end files (R1 and R2), and I am trying to run them with the --paired option. I get an error which seems to suggest that the program thinks there is only a single file with the name of both files (`F08060-L1_S17_L002_R1_001.fastq F08060-L1_S17_L002_R2_001.fastq').

Running on a single file works fine.

Any ideas?

```
python run-bwa.py F08060-L1_S17_L002_R1_001.fastq F08060-L1_S17_L002_R2_001.fastq --fungi --output alignmentstest.sam --paired
[M::bwa_idx_load_from_disk] read 0 ALT contigs
[E::main_mem] fail to open file `F08060-L1_S17_L002_R1_001.fastq F08060-L1_S17_L002_R2_001.fastq'.
```

**Comment by nlapier2** [comment]
Thanks for reporting this bug! I've pushed a commit that should fix this. Let me know if that works for you.

Best,
Nathan

**Comment by SimenHyllHansen** [comment]
Great, it works now! Thanks a lot!
