### ISSUE TITLE
Possible to use more cores?

### ISSUE THREAD

**Issue by SimenHyllHansen** [smangul1/MiCoP#6]
Not sure if it is appropriate to ask things which strictly are not errors, if it is not, I'll delete this at once.

I am simply wondering if there is any way to use more than one core to process each sample faster? I can't run several terminals with several samples in parallel because of memory limitations. Right now each sample takes 3-4 hours with the --fungi option.

-Simen Hyll Hansen

**Comment by nlapier2** [comment]
The run-bwa.py script is meant as a simple helper script for very basic functions for people who are uncomfortable with running BWA themselves, so I don't think I'll be adding multiprocessing support. For advanced options, I'd expect the user to run BWA itself with whatever specifics they desire. The documentation is here: http://bio-bwa.sourceforge.net/bwa.shtml

You can use the "-t" argument to increase the number of threads for BWA. So you'd run something like this if you wanted to use 8 threads :
MiCoP/bwa.kit/bwa mem -t 8 -a MiCoP/data/fungi-refseq.fna pe1.fq pe2.fq > alignments.sam

Best,
Nathan
