### ISSUE TITLE
Raw read counts

### ISSUE THREAD

**Issue by mradz19** [smangul1/MiCoP#7]
Hi, I am interested in comparing the number of reads assigned to bacteria and fungi in human samples. I have used metaphlan2 for bacterial annotation and I was hoping o use MiCoP for fungal annotation. Does the MiCoP output provide raw sequence counts associated with each taxa or is it just relative abundance values?

**Comment by nlapier2** [comment]
Hi,

I've now received multiple requests for an option to output raw read counts instead of relative abundances, so I've now added this feature. Use the --raw_counts option in compute-abundances.py.

Best,
Nathan
